#!/usr/bin/env python3
"""Generate REPORT.md: corpus statistics + paper listings per TME axis.

Narrative synthesis lives in notes/*.md; this file is the auto-generated
evidence table so listings never drift from index.tsv.
"""
import csv
import os
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
IDX = os.path.join(HERE, "index.tsv")
OUT = os.path.join(HERE, "REPORT.md")

LABELS = [
    ("general_tme_modulation", "Cross-cutting TME modulation & immune contexture"),
    ("clinical_resistance", "Mechanisms of immunotherapy resistance (primary & acquired)"),
    ("myeloid_macrophage", "Myeloid compartment: TAMs, MDSCs, neutrophils, phagocytosis checkpoints"),
    ("treg_suppressive_lymphoid", "Suppressive lymphoid compartment: Tregs & T-cell exhaustion"),
    ("caf_stroma_ecm", "CAFs, ECM & TGF-β-driven exclusion"),
    ("vasculature_hypoxia", "Vasculature, hypoxia & vascular normalisation"),
    ("metabolic_tme", "Metabolic TME: adenosine, tryptophan, lactate, lipids"),
    ("innate_agonists", "Innate sensing agonists: STING, TLR, RIG-I, type-I IFN"),
    ("cytokine_engineering", "Engineered & localised cytokines"),
    ("trafficking_tls", "T-cell trafficking, chemokines & tertiary lymphoid structures"),
    ("antigen_presentation_ifn", "Antigen presentation, MHC-I loss & IFN-γ pathway defects"),
    ("epigenetic_priming", "Epigenetic priming & viral mimicry"),
    ("radiation_chemo_priming", "Radiation & chemotherapy priming, immunogenic cell death"),
    ("intratumoral_oncolytic", "Intratumoral therapy, oncolytic viruses & engineered bacteria"),
    ("microbiome", "Microbiome modulation & FMT"),
    ("tme_directed_delivery", "TME-directed delivery & regulated cell death"),
    ("cell_therapy_tme", "Cell therapy against the solid-tumour TME"),
    ("physical_modulation", "Physical & energy-based TME modulation"),
    ("spatial_profiling", "Spatial and single-cell dissection of the TME"),
]
EV_ORDER = ["clinical_trial", "translational_human", "systematic_review", "review",
            "preclinical", "mechanistic"]
EV_LABEL = {"clinical_trial": "Clinical trials", "translational_human": "Human translational",
            "systematic_review": "Evidence synthesis", "review": "Reviews",
            "preclinical": "Preclinical (in vivo)", "mechanistic": "Mechanistic"}


def authors_short(a):
    a = (a or "[no author listed]").rstrip(". ")
    first = a.split(",")[0]
    return f"{first} et al." if "," in a else first


def main():
    rows = list(csv.DictReader(open(IDX), delimiter="\t"))
    by_axis = defaultdict(list)
    for r in rows:
        by_axis[r["axis"]].append(r)

    ev = Counter(r["evidence"] for r in rows)
    dis = Counter(d for r in rows for d in r["disease"].split(";"))
    years = [int(r["year"]) for r in rows if r["year"].isdigit()]
    resist = sum(1 for r in rows if r["resistance"] == "yes")
    ft = sum(1 for r in rows if r["local_fulltext"])

    out = ["<!-- AUTO-GENERATED by gen_report.py; narrative synthesis is in notes/ -->",
           "", "# TME modulation in solid and immunotherapy-resistant tumours — evidence listing",
           "",
           f"{len(rows)} curated records, {min(years)}–{max(years)}. "
           f"{resist} ({100 * resist // len(rows)}%) explicitly address immunotherapy "
           f"resistance, immune exclusion or cold-tumour biology; {ft} have open-access "
           "full text mirrored under `fulltext/` (marked `FT`).", "",
           "**Evidence mix** — " + ", ".join(
               f"{EV_LABEL[k]}: {ev[k]}" for k in EV_ORDER if ev[k]), "",
           "**Disease context** — " + ", ".join(
               f"{k}: {v}" for k, v in dis.most_common()), ""]

    for axis, label in LABELS:
        recs = by_axis.get(axis, [])
        if not recs:
            continue
        yrs = [int(r["year"]) for r in recs if r["year"].isdigit()]
        nres = sum(1 for r in recs if r["resistance"] == "yes")
        out += [f"## {label}", "",
                f"_{len(recs)} papers · {min(yrs)}–{max(yrs)} · {nres} resistance-focused_", ""]
        by_ev = defaultdict(list)
        for r in recs:
            by_ev[r["evidence"]].append(r)
        for evk in EV_ORDER:
            sub = sorted(by_ev.get(evk, []), key=lambda r: r["year"])
            if not sub:
                continue
            out += [f"### {EV_LABEL[evk]}", ""]
            for r in sub:
                mark = " `FT`" if r["local_fulltext"] else ""
                ident = f"PMID {r['pmid']}" if r["pmid"] else (r["doi"] or "")
                out.append(f"- **{r['year']}** {authors_short(r['authors'])} — "
                           f"{r['title']}. *{r['venue']}*. [{ident}]({r['url']}){mark}")
            out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote REPORT.md: {len(rows)} papers, {len(LABELS)} axes")


if __name__ == "__main__":
    main()
