#!/usr/bin/env python3
"""Generate REPORT.md: corpus statistics + paper listings per axis.

Narrative synthesis lives in notes/*.md; this file is the auto-generated
evidence table so listings never drift from index.tsv.
"""
import csv
import os
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
IDX = os.path.join(HERE, "index.tsv")
OUT = os.path.join(HERE, "REPORT.md")

LABELS = [
    ("general_nk_therapy", "Cross-cutting NK-cell therapy landscape"),
    ("nk_phenotype_states", "NK phenotypes & cell states (subsets, adaptive/memory-like, dysfunction)"),
    ("nk_cell_sources", "Cell sources: peripheral blood, cord blood, iPSC, cell lines"),
    ("car_nk_engineering", "CAR-NK & receptor engineering, gene delivery"),
    ("nk_engagers", "NK-cell engagers: BiKE, TriKE, NKp46/CD16 engagers"),
    ("gene_editing_knockouts", "Gene editing: checkpoint and brake knockouts"),
    ("cytokine_support", "Cytokine support & armouring (IL-15, IL-21, IL-12/15/18, IL-18)"),
    ("expansion_feeders", "Ex vivo expansion, feeders, media & GMP manufacturing"),
    ("cryo_qc_manufacturing", "Cryopreservation, potency assays & product quality"),
    ("metabolism_persistence", "Metabolic fitness, hypoxia & in vivo persistence"),
    ("checkpoints_inhibitory", "Inhibitory receptors, checkpoints & tumour escape"),
    ("adcc_combinations", "ADCC, antibody and drug combinations"),
    ("trafficking_solid_tme", "Trafficking, homing & the solid-tumour microenvironment"),
    ("clinical_nk", "Clinical evidence: adoptive NK, CAR-NK, memory-like NK"),
]
EV_ORDER = ["clinical_trial", "translational_human", "process_method", "preclinical",
            "mechanistic", "systematic_review", "review"]
EV_LABEL = {"clinical_trial": "Clinical trials", "translational_human": "Human translational",
            "process_method": "Process / manufacturing methods",
            "preclinical": "Preclinical (in vivo)", "mechanistic": "Mechanistic / in vitro",
            "systematic_review": "Evidence synthesis", "review": "Reviews"}


def authors_short(a):
    a = (a or "[no author listed]").rstrip(". ")
    first = a.split(",")[0]
    return f"{first} et al." if "," in a else first


def main():
    rows = list(csv.DictReader(open(IDX), delimiter="\t"))
    by_axis = defaultdict(list)
    for r in rows:
        by_axis[r["axis"]].append(r)

    ev = Counter(r["evidence"] for r in rows)
    dis = Counter(d for r in rows for d in r["disease"].split(";"))
    years = [int(r["year"]) for r in rows if r["year"].isdigit()]
    manuf = sum(1 for r in rows if r["manufacturing"] == "yes")
    ft = sum(1 for r in rows if r["local_fulltext"])

    out = ["<!-- AUTO-GENERATED by gen_report.py; narrative synthesis is in notes/ -->",
           "", "# NK cells for cancer — evidence listing", "",
           f"{len(rows)} curated records, {min(years)}–{max(years)}. "
           f"{manuf} ({100 * manuf // len(rows)}%) report expansion, culture or "
           f"manufacturing content; {ft} have open-access full text mirrored under "
           "`fulltext/` (marked `FT`).", "",
           "**Evidence mix** — " + ", ".join(
               f"{EV_LABEL[k]}: {ev[k]}" for k in EV_ORDER if ev[k]), "",
           "**Disease context** — " + ", ".join(
               f"{k}: {v}" for k, v in dis.most_common()), ""]

    for axis, label in LABELS:
        recs = by_axis.get(axis, [])
        if not recs:
            continue
        yrs = [int(r["year"]) for r in recs if r["year"].isdigit()]
        nman = sum(1 for r in recs if r["manufacturing"] == "yes")
        out += [f"## {label}", "",
                f"_{len(recs)} papers · {min(yrs)}–{max(yrs)} · {nman} with "
                "culture/manufacturing content_", ""]
        by_ev = defaultdict(list)
        for r in recs:
            by_ev[r["evidence"]].append(r)
        for evk in EV_ORDER:
            sub = sorted(by_ev.get(evk, []), key=lambda r: r["year"])
            if not sub:
                continue
            out += [f"### {EV_LABEL[evk]}", ""]
            for r in sub:
                mark = " `FT`" if r["local_fulltext"] else ""
                ident = f"PMID {r['pmid']}" if r["pmid"] else (r["doi"] or "")
                out.append(f"- **{r['year']}** {authors_short(r['authors'])} — "
                           f"{r['title']}. *{r['venue']}*. [{ident}]({r['url']}){mark}")
            out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote REPORT.md: {len(rows)} papers, {len(by_axis)} axes")


if __name__ == "__main__":
    main()
